- name: Create ops directory
  file:
    path: /home/ubuntu/ops
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  tags: deploy

- name: Copy ops folder contents (except .env)
  copy:
    src: "{{ playbook_dir }}/../ops/"
    dest: /home/ubuntu/ops/
    owner: ubuntu
    group: ubuntu
    mode: preserve
  tags: deploy

- name: Create .env file with secrets
  template:
    src: env.j2
    dest: /home/ubuntu/ops/.env
    owner: ubuntu
    group: ubuntu
    mode: '0600'  # Only readable by owner
  tags: deploy

- name: Restart docker compose
  shell: |
    cd /home/ubuntu/ops
    docker compose down || true
    docker compose up -d
  tags: deploy