- name: Create ops directory
  file:
    path: /home/ubuntu/ops
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  tags: deploy

- name: Copy ops folder contents
  copy:
    src: "{{ playbook_dir }}/../ops/"
    dest: /home/ubuntu/ops/
    owner: ubuntu
    group: ubuntu
    mode: preserve
    backup: yes
  tags: deploy

- name: Stop existing containers
  shell: |
    cd /home/ubuntu/ops
    docker compose down || true
  ignore_errors: yes
  tags: deploy

- name: Start docker compose services
  shell: |
    cd /home/ubuntu/ops
    docker compose up -d
  tags: deploy
  register: compose_result

- name: Show docker compose status
  debug:
    msg: "Docker Compose Result: {{ compose_result.stdout }}"
  tags: deploy