version: "3.9"
services:
  web-dev:
    container_name: web-dev
    image: ${DOCKER_IMAGE}:${TAG}
    ports:
      - "8082:3000"                 # DEV: VM port 8082 → container port 3000
    environment:
      - NODE_ENV=production
      - METRICS_ENABLED=true
    env_file:
      - ./app.env                   # optional, NEXT_PUBLIC_* vars etc.
    restart: unless-stopped
    labels:
      - "prometheus.scrape=true"
      - "prometheus.port=3000"
      - "prometheus.path=/api/apps/metrics"
