global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nextjs-app"
    metrics_path: /api/metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["136.112.147.14:8080"] # if app runs on VM directly

  - job_name: "jenkins"
    metrics_path: /prometheus
    scrape_interval: 30s
    basic_auth:
      username: '${JENKINS_USER}'
      password: '${JENKINS_TOKEN}'
    static_configs:
      - targets: ["jenkins:8080"] # container name inside Docker network

  - job_name: "docker-containers"
    static_configs:
      - targets: ["dockerhost:9323"]
